### ISSUE TITLE
Stolen content is frowned upon

### ISSUE THREAD

**Issue by UberGuidoZ** [germansquid/flipping_stuff#1]
I noticed a lot of content in your repo has been lifted, apparently from [my well-established repo](https://github.com/UberGuidoZ/Flipper), and creations have had the author name changed. This is _heavily_ frowned upon and frequently does not work in your favor. We're a helpful bunch and happy to share (that's why it's there) but proper credit is appreciated.

Hopefully, you're able to contribute some of your own original work too.

**Comment by stautonico** [comment]
At least just fork the original repo and make your modifications...

**Comment by germansquid** [comment]
Guys, sorry for that. Wanted to keep it private until i could add something relevant on my own. 
Sry for not forking you m8. This should never go live in this form!
@UberGuidoZ i even asked you about parts of your code. I just wanted to keep that put here until i could resolve my errors and then build something own out of that. 
I keep you as author noticed in every file which is or contains stuff from your repo. 
I had no intent in stealing from anyone, I promise.

I just wish i kept this one private for a week longer to clean up and credit the owners in a more respectful matter.
Tell me if this is ok for you? Again, in every file you or the other authors are named. 
I also wanted to use the content mainly not to just host it. I got a lot of ppl asking how to do that stuff and i wanted to lecture and comment the source code. 
Short term, I am focussing on delivering code that runs on qwertz keyboard layouts. So you can try it and adapt it on your own. I just got quite some dms on discord from those who couldn't get BadUSB running on other then us-layouts. 

So pls check again from tomorrow on, if i still didn't credited in a respectfull way. I never had the intend on "stealing", "lifting" or anything else then helping so solve issues without copy pasting the solution for the 20th time.

**Comment by germansquid** [comment]
Edit: Read your comment again: 
`creations have had the author name changed`
Sadly true. I pasted most origins code in a original with correct formatting e.g.
Again my point above: I am sorry, this took off before i was able to get shit fixed. So far i checked every file and can ensure that at least in there are the credits with correct authors/repos/github names/links and more.
Check in again tomorrow pls and tell me if you can give the permission to close this issue.
If not, pls tell me what is still missing and i'll fix it asap.

**Comment by UberGuidoZ** [comment]
Thank you for your thoughtful response. Word to the wise: If you're not ready to share your stuff, keep it private, and don't spam the link around discord. ;-) As I said, we're a helpful bunch and will share what we can. Always on the lookout for new things to check out, learn from, and collaborate with.

I trust that you have reviewed things as I've heard from a number of others things were corrected. I'm not here to police your repo or what you do - merely an observation with a recommended action to correct before things went down an undesirable path. I commend you for taking the high road.

Hope to see you around!

**Comment by germansquid** [comment]
Imagine someone could have had the awareness and branched the new stuff, that wasn't ready for public in the first place or kept it private as a whole.  Next time with more then once brain cell active stuff like this should not happen again.
Repo should be fine now and will stay that way for sure. If i have had more time the first night, it could have been like this from the beginning.
Thanks for the chance to get this right.
